spring.application.name=gestor

# datasource 
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:gestor
spring.datasource.username=sa
spring.datasource.password=

# jpa 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
spring.jpa.hibernate.format_sql=true